import { Link } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <Link to="/">
          <Button variant="ghost" className="mb-6">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
        </Link>

        <Card>
          <CardHeader>
            <CardTitle className="text-3xl">Terms of Service</CardTitle>
            <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
          </CardHeader>
          <CardContent className="prose prose-sm max-w-none space-y-6">
            <section>
              <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground">
                By accessing and using this AI Sports Coaching application, you accept and agree to be bound by 
                the terms and provisions of this agreement. If you do not agree to these terms, please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
              <p className="text-muted-foreground">
                We provide an AI-powered sports performance analysis platform that:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                <li>Analyzes video uploads of athletic performances</li>
                <li>Generates automated coaching feedback and recommendations</li>
                <li>Tracks performance metrics and progress over time</li>
                <li>Provides personalized training insights</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">3. User Accounts and Responsibilities</h2>
              <p className="text-muted-foreground">You are responsible for:</p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Ensuring the accuracy of information you provide</li>
                <li>Complying with all applicable laws when using the service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">4. Usage Limits and Rate Limiting</h2>
              <p className="text-muted-foreground">
                To ensure fair usage and service availability, we implement the following rate limits:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                <li>Video analysis: 10 analyses per hour</li>
                <li>Clip analysis: 30 analyses per hour</li>
                <li>Feedback generation: 20 reports per hour</li>
              </ul>
              <p className="text-muted-foreground mt-2">
                Excessive usage beyond these limits may result in temporary restrictions or account suspension.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">5. Content and Intellectual Property</h2>
              <p className="text-muted-foreground">
                You retain ownership of the videos and content you upload. By uploading content, you grant us 
                a license to process, analyze, and store your content solely for the purpose of providing our services.
              </p>
              <p className="text-muted-foreground mt-2">
                All analysis reports, feedback, and recommendations generated by our AI are provided for informational 
                and educational purposes only.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">6. AI-Generated Analysis Disclaimer</h2>
              <p className="text-muted-foreground">
                Our AI-powered analysis is designed to assist in sports training but should not replace:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                <li>Professional coaching advice from qualified instructors</li>
                <li>Medical advice from healthcare professionals</li>
                <li>Judgment regarding safety and injury prevention</li>
              </ul>
              <p className="text-muted-foreground mt-2">
                <strong>Always consult with qualified coaches and medical professionals before making training decisions.</strong>
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">7. Prohibited Uses</h2>
              <p className="text-muted-foreground">You agree not to:</p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                <li>Upload content that violates any laws or third-party rights</li>
                <li>Attempt to circumvent rate limits or security measures</li>
                <li>Use the service for unauthorized commercial purposes</li>
                <li>Reverse engineer or attempt to extract our AI models</li>
                <li>Share your account credentials with others</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">8. Minors and Parental Consent</h2>
              <p className="text-muted-foreground">
                If you are under 18 years of age, you must have parental or guardian consent to use this service. 
                Parents and guardians are responsible for monitoring their children's use of the platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">9. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                This service is provided "as is" without warranties of any kind. We are not liable for:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                <li>Injuries or damages resulting from following AI-generated recommendations</li>
                <li>Accuracy or completeness of AI analysis and feedback</li>
                <li>Loss of data or service interruptions</li>
                <li>Any indirect, incidental, or consequential damages</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">10. Account Termination</h2>
              <p className="text-muted-foreground">
                We reserve the right to suspend or terminate accounts that violate these terms or engage in 
                abusive behavior. You may delete your account at any time through account settings.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">11. Changes to Terms</h2>
              <p className="text-muted-foreground">
                We may modify these terms at any time. Continued use of the service after changes constitutes 
                acceptance of the modified terms. Material changes will be communicated through the application.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">12. Contact and Support</h2>
              <p className="text-muted-foreground">
                For questions about these terms or support issues, please use the feedback features in the 
                application or contact us through your account settings.
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default TermsPage;
