// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbmguhdrrhbuzzztqprj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRibWd1aGRycmhidXp6enRxcHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzNjUyNDgsImV4cCI6MjA0ODk0MTI0OH0.Khtkb8sDOpM_Uuk_wAG8vi-nP0Qrx9Y5WqbSw6T6yVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);