
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aghjbyysvchicvekbamg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnaGpieXlzdmNoaWN2ZWtiYW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1OTM0MjcsImV4cCI6MjA1ODE2OTQyN30.5hk968nnBF4byY4Jc8edTlDkdRd7XMZ5uPua_6-EiJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
